# Generated by Django 3.0.6 on 2020-06-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetpost',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Account'),
        ),
    ]
