# Generated by Django 3.0.6 on 2020-06-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budgetpost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetpost',
            name='comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
