# Generated by Django 3.0.6 on 2020-05-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Category',
            new_name='category',
        ),
    ]
