# Generated by Django 3.0.6 on 2020-06-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200607_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('expence', 'expence'), ('deposit', 'deposit')], default='expece', max_length=8, null=True),
        ),
    ]
