# Generated by Django 3.0.6 on 2020-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('expence', 'expence'), ('deposit', 'deposit')], default='expence', max_length=8, null=True),
        ),
    ]
